[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

[[edge_functions]]
function = "server"
path = "/*"
excludedPath = [
  "/build/*",
  "/favicon.ico",
  "/robots.txt"
]

[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"
